### Add Idea

POST http://localhost:3001/api/idea HTTP/1.1
content-type: application/json

{   
    "method": "CREATE",
    "idea": {
        "info": "FA",
        "description": "2wda"
    }
}

### Update Idea

POST http://localhost:3001/api/idea HTTP/1.1
content-type: application/json

{   
    "method": "UPDATE",
    "idea": {
        "id": "0",
        "info": "ASDASD",
        "description": "ASDASD"
    }
}

### Delete Idea

POST http://localhost:3001/api/idea HTTP/1.1
content-type: application/json

{   
    "method": "DELETE",
    "idea": {
        "id": "1"
    }
}

### Get All Idea

GET http://localhost:3001/api/idea HTTP/1.1


### Get Idea

GET http://localhost:3001/api/idea/2 HTTP/1.1

### Get Word

GET http://localhost:3001/api/idea/generate/10 HTTP/1.1


